inherit_gem:
  srp-style:
    - rubocop.yml
    - rubocop_performance.yml
    - rubocop_rake.yml
    - rubocop_rspec.yml

AllCops:
  Exclude:
    - bin/**/*

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

# Lots of spec examples break across multiple lines.
Style/MethodCallWithArgsParentheses:
  Exclude:
    - spec/**/*
    - Gemfile
    - Rakefile

RSpec/NamedSubject:
  Enabled: false

